INSERT INTO DEPARTMENT (DEPARTMENT_NAME) values ('無所属'),('営業部'),('企画部'),('開発部');

INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT_ID, GENDER) VALUES ('dummy', 'ダミー', 1, 'FEMALE'), ('dummy2', 'ダミー2', 2, 'MALE');
INSERT INTO PERSONAL (EMPLOYEE_ID, BIRTHDAY, TELEPHONE_NUMBER, MAIL_ADDRESS) VALUES ('dummy', '2023-01-01', '00000000000', 'dummy@gmail.com'), ('dummy2', '2023-01-01', '00000000002', 'dummy2@gmail.com');
INSERT INTO HISTORY (EMPLOYEE_ID, START_DATE, DEPARTMENT_ID, CONTENT) VALUES ('dummy', '2022-01-01', 2, 'ダミー入社');
INSERT INTO HISTORY (EMPLOYEE_ID, START_DATE, DEPARTMENT_ID, CONTENT) VALUES ('dummy', '2023-01-01', 1, 'ダミー退職');
INSERT INTO HISTORY (EMPLOYEE_ID, START_DATE, DEPARTMENT_ID, CONTENT) VALUES ('dummy2', '2022-02-02', 2, 'ダミー2入社');