set mode MySQL;

CREATE TABLE IF NOT EXISTS DEPARTMENT (
  DEPARTMENT_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  DEPARTMENT_NAME VARCHAR(256) NOT NULL,
  CREATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS EMPLOYEE (
  EMPLOYEE_ID VARCHAR(10) NOT NULL PRIMARY KEY,
  DEPARTMENT_ID BIGINT NOT NULL,
  EMPLOYEE_NAME VARCHAR(256) NOT NULL,
  GENDER VARCHAR(256) NOT NULL,
  CREATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PERSONAL (
  EMPLOYEE_ID VARCHAR(10) NOT NULL PRIMARY KEY,
  BIRTHDAY DATE NOT NULL,
  TELEPHONE_NUMBER VARCHAR(256) NOT NULL,
  MAIL_ADDRESS VARCHAR(256) NOT NULL,
  CREATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS HISTORY (
  EMPLOYEE_ID VARCHAR(10) NOT NULL,
  START_DATE DATE NOT NULL,
  DEPARTMENT_ID BIGINT NOT NULL,
  CONTENT VARCHAR(256),
  CREATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT UQ_HISTORY UNIQUE (EMPLOYEE_ID, START_DATE, DEPARTMENT_ID)
);